### ISSUE TITLE
Set width and height of cropbox

### ISSUE THREAD

**Issue by CubanDude** [bupy7/yii2-widget-cropbox#17]
Is there a way to set the width and height of the cropbox and to not make it resizeable? I saw the properties in the .js file, but I wonder if there's another way than editing the file.

**Comment by bupy7** [comment]
Hi. You can to set CSS properties for weight and height:
```css
.workarea-cropbox,
.bg-cropbox {
    height: 500px;
    min-height: 500px;
    width: 500px;
    min-width: 500px;
}
```
